spring.application.name=clyvo-vet
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rm563558}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:230707}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# JWT — TROCAR O SECRET EM PRODUCAO (minimo 32 caracteres)
app.jwt.secret=${APP_JWT_SECRET:clyvovet-2026-fiap-secret-key-change-in-production!!}
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000
